### ISSUE TITLE
大佬 能不能写一下怎么使用呀，微信企业id这些在哪里添加

### ISSUE THREAD

**Issue by zhaoyanxue666** [skywolf627/VmessActions#1]

**Comment by gtang8** [comment]
同求！

**Comment by skywolf627** [comment]
> _No description provided._



> 同求！


通过GitHub的actions 自动采集节点 
自动生成订阅信息

订阅内容自动更新再仓库的 clash.yml 和 v2ray.txt 中
然后PC端/手机端根据自己的软件支持的格式，订阅对应的链接即可

比如clash.yml的订阅链接为 https://raw.githubusercontent.com/skywolf627/VmessActions/main/clash.yml  
如果自己的仓，直接查看对应文件的raw链接 即可

部分国内网络貌似无法直接访问  https://raw.githubusercontent.com  会导致你的软件第一次拉取订阅的时候 拉取不到节点。这个时候手动在github找到对应的订阅文件，打开文件把节点信息手动录入到软件即可。或者自己找个免费梯子用来拉取节点。

目前抓取的节点速度看youtubu 4k 不卡，电报基本秒开。



现在不推送微信了，直接订阅链接 自动更新

**Comment by gtang8** [comment]
![image](https://user-images.githubusercontent.com/74369627/119335080-748ae580-bcbe-11eb-8763-21aeaef5ade5.png)
在“推送更改”这一步报错：
0s
Run ad-m/github-push-action@master
Push to branch main
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by skywolf627** [comment]
> ![image](https://user-images.githubusercontent.com/74369627/119335080-748ae580-bcbe-11eb-8763-21aeaef5ade5.png)
> 在“推送更改”这一步报错：
> 0s
> Run ad-m/github-push-action@master
> Push to branch main
> Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
> Error: Invalid exit code: 1
> at ChildProcess. (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
> at ChildProcess.emit (events.js:210:5)
> at maybeClose (internal/child_process.js:1021:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
> code: 1
> }
> Error: Invalid exit code: 1
> at ChildProcess. (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
> at ChildProcess.emit (events.js:210:5)
> at maybeClose (internal/child_process.js:1021:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

哦 这个是之前用微信推送 加的TOKEN，现在可以移除了，我改一下

**Comment by skywolf627** [comment]
已更改

**Comment by gtang8** [comment]
![image](https://user-images.githubusercontent.com/74369627/119434871-a72eef80-bd4b-11eb-8248-2b853fe7d0d8.png)
继续在“提交更改”报错

**Comment by skywolf627** [comment]
你自己看看错误信息啊- - 
是因为没有任何更改 然后还提交  所以出错啊- -

**Comment by skywolf627** [comment]
因为早上改了你上面提的问题后 我手动运行了一次，已经采集了最新的节点信息了

所以你这个时候再去采集，节点信息没有变，所以提交会出现这个提示。

不用管就行了，等下午自动运行的时候  你再看是否成功

一天会采集两次的 ，不需要手动更新

如果你要测试，你可以手动删掉那两个文件 ，或者清空文件内容后 ，再手动触发

**Comment by gtang8** [comment]
成功！多谢老大！

**Comment by gtang8** [comment]
昨天到今天都没有更新，我删除了clash.yml 和v2ray.txt，再重新手动运行也是不成功。
![image](https://user-images.githubusercontent.com/74369627/119642063-eabd5280-be4c-11eb-906c-cd85de4c630c.png)
![image](https://user-images.githubusercontent.com/74369627/119642095-f27cf700-be4c-11eb-8d62-057637336e6d.png)

再回头看看你的Action，貌似同样不成功。
![image](https://user-images.githubusercontent.com/74369627/119642122-fad53200-be4c-11eb-8bbc-9751738986e6.png)

**Comment by skywolf627** [comment]
失败也很正常啊，毕竟是采集的别人的节点啊- -
昨天的节点又不是不能用- - ，等明天 后天再看咯， 别激动
