### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by zwengr1** [skywolf627/VmessActions#3]
![截屏2021-06-04 20 40 41](https://user-images.githubusercontent.com/33999768/120802577-2bb41600-c575-11eb-9720-a70b9141dcce.png)

**Comment by skywolf627** [comment]
不用管 偶尔失败很正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月4日(周五) 晚上8:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [skywolf627/VmessActions] 请求帮助 (#3)

**Comment by zwengr1** [comment]
> 不用管 偶尔失败很正常
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2021年6月4日(周五) 晚上8:41
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.***&gt;;
> 主题: [skywolf627/VmessActions] 请求帮助 (#3)
> 
> 
> 
> 
>  
> 
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢了
